### ISSUE TITLE
how to export expression level data

### ISSUE THREAD

**Issue by xuwenjian85** [gagneurlab/OUTRIDER#24]
I am using OUTRIDER to analyze RNA-seq data set. I am trying to save “controlled gene counts” data for my own downstream pipeline. It seems there is no straight forward way to get this controlled data. I found that the variable `ods@assays$data$counts` is the raw counts. Could you give some help?

**Comment by vyepez88** [comment]
Hi, 
The way to extract the controlled gene counts is by doing:
`counts(ods, normalized = TRUE)`

Best,
Vicente

**Comment by xuwenjian85** [comment]
That's what I am looking for. I get it now. Thanks, Vicente.
