### ISSUE TITLE
Ubuntu Groovy doesn't have libmysqld-dev

### ISSUE THREAD

**Issue by drtconway** [gagneurlab/OUTRIDER#31]
Hi Outriders,

Thanks for making a terrific package.

Just to let you know that for licensing reasons, Ubuntu Groovy doesn't have `libmysqld-dev` but it does have `libmariadbd-dev`. It appears to work as a drop in replacement, so you may wish to update your installation instructions.

Tom.

**Comment by c-mertes** [comment]
thanks for the hint. Its changed now.
