### ISSUE TITLE
Description of each column from results() function

### ISSUE THREAD

**Issue by iaradsouza1** [gagneurlab/OUTRIDER#35]
This package is really useful, but I would suggest improving the documentation on the `results()` function. Some of the columns from the dataframe produced by results() are straightforward to understand, however, some are not. I didn't find their description either in the function documentation or in the vignette.

For example, is the `theta` column the dispersion parameter? Is the `meanCorrected` the mean of the distribution for that gene without the outlier count? 

Thanks for this tool

**Comment by brechtmann** [comment]
Hi, 
thanks for raising this we will work on that. 

Yes `theta` is the dispersion parameter of the negative binomial distribution for that gene.
`meanCorrected` is the expected count given our fitted autoencoder model. We should maybe rename that. It is not the mean without the outlier. When you go to the paper `meanCorrected` is `c_ij` as defined by Equation 2.

I hope this helps.

**Comment by c-mertes** [comment]
@brechtmann can you please check the documentation in #52
