### ISSUE TITLE
Installation issues with R aarch64-apple-darwin20

### ISSUE THREAD

**Issue by ricorona** [gagneurlab/OUTRIDER#50]
I have an Apple M1 Pro Chip and I cannot install OUTRIDER. I was using another R version before, but once I changed to this R version, I cannot install it any longer.

**Comment by c-mertes** [comment]
can you give a bit more specifics? Which R version worked and which R version does not work? Also which Bioconductor version and OUTRIDER version are you using? I assume you use BioManager::install("OUTRIDER") to install it.

Can you give use the error message? 

Best,
Christian

**Comment by ricorona** [comment]
Sure, the R version I was using was: 

R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Monterey 12.6

Now I installed:

R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

I am trying to install OUTRIDER by using:

BiocManager::install("OUTRIDER")

It tries to install from sources, but it cannot install one dependency, so then the installation of OUTRIDER fails. This is the error message I get:

cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
         ^~~~~~~~
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rhtslib’
ERROR: dependency ‘Rhtslib’ is not available for package ‘Rsamtools’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rsamtools’
ERROR: dependency ‘Rsamtools’ is not available for package ‘GenomicAlignments’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/GenomicAlignments’
ERROR: dependencies ‘Rsamtools’, ‘GenomicAlignments’ are not available for package ‘rtracklayer’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/rtracklayer’
ERROR: dependency ‘rtracklayer’ is not available for package ‘GenomicFeatures’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/GenomicFeatures’
ERROR: dependency ‘GenomicFeatures’ is not available for package ‘OUTRIDER’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/OUTRIDER’

**Comment by c-mertes** [comment]
Dear @ricorona thanks for the output and sorry for the late response. This looks like you do not have all the header files to compile the dependencies. Based on your error code you have to install lzma.h. There might come up more of those missing header files. 

```
cram/cram_io.c:61:10: fatal error: 'lzma.h' file not found
#include <lzma.h>
^~~~~~~~
1 error generated.
make[1]: *** [cram/cram_io.o] Error 1
make: *** [htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’
 ```
 
 Maybe it is enough to reinstall xz using homebrew
 
 ```
 ```
 
 Else you can check out the two posts 
 https://github.com/samtools/htslib/issues/493
 https://discussions.apple.com/thread/7895857

**Comment by c-mertes** [comment]
I will close this issue as it is rather an upstream error and not too much related to OUTRIDER. Please reopen it if you face still issues with this.
