### ISSUE TITLE
Overexpression of TBR1 not found

### ISSUE THREAD

**Issue by juugeebee** [gagneurlab/OUTRIDER#71]
Hi, 

The attached ppt presents the case of overexpression of TBR1 due to a PSMD14/TBR1 fusion on patient 6624CY000185. 
We ran OUTRIDER via DROP and this variant was not found. 

You can find in that link the raw OUTRIDER outputs files and the DROP config file : 
https://dispose.aphp.fr/u/8c_Zd35P2Xrjz9lo/86866af4-a635-48d1

Would you have any clues that could explain why the tool does not find the variant?
[PSMD14-TBR1.pptx](https://github.com/user-attachments/files/17378417/PSMD14-TBR1.pptx)

Thanks in advance for your help! 
Julie Bogoin

**Comment by vyepez88** [comment]
answered here: https://github.com/gagneurlab/drop/issues/583
