### ISSUE TITLE
Using pre-trained autoencoder for speedup

### ISSUE THREAD

**Issue by fbattke** [gagneurlab/OUTRIDER#73]
Hi, thanks for developing and sharing this package!

Please forgive me if this question makes no sense at all, I'm new to autoencoders. 

I'm looking for a way to iteratively compute aberrant expression for new samples, without running the whole fit every time I have a new sample to analyze. Is there a way to do that, perhaps along these lines?:

- Fit the autoencoder (i.e., do a full OUTRIDER() run) on a matrix with 250 samples once and store the result
- Later, reload that matrix, swap one of the samples with a newly sequenced one.
- Then apply the AE to the new sample and compute aberrant expression for that new sample only?

Best,
Florian

**Comment by vyepez88** [comment]
Hi Florian,
Thanks for using our tools. The current AE implementation requires to run the full matrix. We have tried ways of doing what you suggest, i.e., masking a sample and adding it at a later stage, but with suboptimal results (same for FRASER). 
Best,
Vicente

**Comment by fbattke** [comment]
Hi Vicente,
thanks for the quick reply. Suboptimal results are not what I wanted, so I won't pursue this further. ;)
Best,
Florian
